apiVersion: v1
kind: Service
metadata:
  name: mariadb-nodeport
  namespace: rgz
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306   # можно выбрать любой свободный порт в диапазоне 30000-32767
  type: NodePort
